# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set the theme to agnoster (cleaner theme).
ZSH_THEME="agnoster"

# Plugins to enable
plugins=(
    git                    # Git shortcuts
    zsh-autosuggestions     # Command suggestions based on history
    zsh-syntax-highlighting # Syntax highlighting for commands
    zsh-completions        # Tab completions for commands
    zsh-history-substring-search # Search through command history using arrows
    virtualenv             # Python virtual environment support
    virtualenvwrapper      # More convenient Python env management
    # z                     # Removed as per your request
)

# Source Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Enable virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
source /usr/bin/virtualenvwrapper.sh

# Set up Pyenv (Optional) for managing Python versions
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Aliases
alias ll='ls -la'
alias gs='git status'
alias gp='git pull'
alias gd='git diff'
alias activate="source venv/bin/activate"   # Shortcut to activate Python virtual env
alias deactivate="deactivate"                # Shortcut to deactivate Python virtual env

# History substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Zsh history settings
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Automatically activate virtualenv when changing directories if venv is found
autoload -U add-zsh-hook

function auto-activate-virtualenv() {
  if [[ -e "venv/bin/activate" ]]; then
    source venv/bin/activate
  elif [[ -n $VIRTUAL_ENV ]]; then
    deactivate
  fi
}

add-zsh-hook chpwd auto-activate-virtualenv
auto-activate-virtualenv

# Set the prompt to show date, time, user, host, and current directory
PROMPT='[%D{%Y-%m-%d} %*] %F{cyan}%n%f@%F{yellow}%m%f %F{green}%~%f %# '

# Zsh options
setopt autocd             # Auto switch to directories without 'cd'
setopt append_history     # Append to history file instead of overwriting
setopt hist_ignore_dups   # Don't store duplicate commands in history
setopt share_history      # Share history between all terminals

export PATH=$PATH:/home/x/.spicetify
